services:
  wp-db:
    extends:
      file: docker-compose.yml
      service: wp-db
    restart: always
    container_name: wp-mariadb-prod

  wordpress:
    extends:
      file: docker-compose.yml
      service: wordpress
    restart: always
    container_name: wp-app-prod
    environment:
      WORDPRESS_DB_HOST: wp-mariadb-prod
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://yu-syumilog.com');
        define('WP_SITEURL', 'https://yu-syumilog.com');
        define('WP_DEBUG', true);
        define('WP_DEBUG_DISPLAY', true);